import type { Metadata } from "next";
import Menu from "./menu.tsx";
import Image from 'next/image';
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <Menu></Menu>
        <div className="workPlace">
          <div className="workFrame">
            {children}
          </div>
          <div className="buttom">
            <p>
              powered by:
            </p>
            <Image
              src='/smg-group-logo.webp'
              alt='Surelock McGill Group Logo'
              width={176}
              height={60}
            />
          </div>
        </div>
      </body>
    </html>
  );
}
