import type { Metadata } from "next";
import Image from 'next/image';
import Link from 'next/link';
import { Geist, Geist_Mono } from "next/font/google";
import Menu from "@view/menu";
import Back from "@view/back";
import "@css/globals";
import "./globals.css";
import "@css/layout";
import "@css/input";
import "@css/image";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <div className="sideMenu">
          <Menu />
        </div>
        <div className="workPlace">
          <div className="backMenu">
            <Back />
          </div>
          <div className="workFrame">
            {children}
          </div>
          <div className="buttom">
            <p>
              powered by:
            </p>
            <Link
              href="/"
            >
              <Image
                src='/smg-group-logo.webp'
                alt='Surelock McGill Group Logo'
                width={176}
                height={60}
              />
            </Link>
          </div>
        </div>
      </body>
    </html>
  );
}
